# Week 2 Part 2 Assignment - Centrality Measures
# Group 5: Ashish Kumar, Christina Valore, Zachary Herold, Isabel Ramesar

***

1. [Objective](#Objective)
2. [Data Set](#Data_Set)
3. [Data Load](#Data_Load)
4. [Hypothetical Outcome](#Hypothetical_Outcome)
5. [Video Presentation](#Video_Presentation)

***
<a id="Objective"></a>
## Objective

<font color=green> Centrality measures can be used to predict (positive or negative) outcomes for a node. Your task in this week’s assignment is to identify an interesting set of network data that is available on the web (either through web scraping or web APIs) that could be used for analyzing and comparing centrality measures across nodes.  As an additional constraint, there should be at least one categorical variable available for each node (such as “Male” or “Female”; “Republican”, “Democrat,” or “Undecided”, etc.) In addition to identifying your data source, you should create a high level plan that describes how you would load the data for analysis, and describe a hypothetical outcome that could be predicted from comparing degree centrality across categorical groups. </font>

<a id="Data_Set"></a>
## Data Set

<font color=green> An interesting data set (https://www.kaggle.com/miroslavsabo/young-people-survey/downloads/responses.csv/data) we found was a survey of Hobbies and Interest of individuals. 

We will build a network structure wherein Hobbies and Interest are the primary nodes, and other Hobbies and Interest are associate with them (as edges). In this way we will be able to examine relationships between Hobbies and Interest. The categorical variable we will be using is Gender and Upbringing Location (City/village). 
</font>

<a id="Data_Load"></a>
## Data Load

<font color=green> We will use the following code to import the csv into Python.</font>

In [4]:
import pandas as pd

import os

variable =pd.read_csv('https://raw.githubusercontent.com/ashishsm1986/data620-Assignment-project-grp5/master/responses.csv?token=AGTMN6VQDW7CQ44RFG7R6EC5BALG2')

variable.head()

,Music,Slow songs or fast songs,Dance,Folk,Country,Classical music,Musical,Pop,Rock,Metal or Hardrock,...,Age,Height,Weight,Number of siblings,Gender,Left - right handed,Education,Only child,Village - town,House - block of flats
0,5,4,2.0,2,3,4,5,4.0,3,1,...,27.0,170.0,70.0,1.0,female,right handed,masters degree,no,city,block of flats
1,4,4,4.0,2,1,3,3,4.0,4,1,...,25.0,170.0,67.0,1.0,female,right handed,masters degree,no,village,block of flats
2,5,4,5.0,2,2,4,3,5.0,4,1,...,27.0,181.0,78.0,1.0,male,right handed,masters degree,no,NaN,block of flats
3,5,3,2.0,1,4,5,3,2.0,1,1,...,22.0,190.0,80.0,1.0,male,right handed,masters degree,no,city,block of flats
4,4,3,4.0,3,3,3,2,4.0,5,3,...,24.0,179.0,65.0,3.0,male,right handed,masters degree,no,city,block of flats

<font color=green> We will use then use networkx to build the graph of the network and compute degree centrality for each observation.</font>

<a id="Hypothetical_Outcome"></a>
## Hypothetical Outcome

<font color=green>We hypothesize that higher centrality will be seen among Interest that are technology based.</font>

<a id="Video_Presentation"></a>
## Video Presentation:
<font color=green>https://www.youtube.com/watch?v=qjoZwiTj7Ps&feature=youtu.be</font>